### ISSUE TITLE
Adding *dist* folder by default, for client uses.

### ISSUE THREAD

**Issue by threeday0905** [xtemplate/xtemplate#60]
In our project, we want to download xtemplate via bower ( or npm ) in local.

Could you please add dist folder by default, so that we can use the download-version without manually build in bower_components (or node_modules) folder.

**Comment by yiminghe** [comment]
do not want build in source control, it can exist in npm

**Comment by threeday0905** [comment]
Maybe we can create another repo to host build files, for bower user.  like: angular <http://github.com/angular/bower-angular>

Otherwise it is no way to download build-files directly via bower or npm.

**Comment by threeday0905** [comment]
Oops, I miss the commit#079d61c, please ignore my prev post.
