### ISSUE TITLE
通过自动化测试来验证变更的向前兼容

### ISSUE THREAD

**Issue by dead-horse** [xtemplate/xtemplate#61]
模板引擎有自己的特殊之处，除了语法支持外，还有一个 runtime，在每一个版本发布的时候，我们的语法可以确定是向前兼容的，但是 runtime 是否向前兼容则比较难肉眼看出来，特别是有一些大的变更的时候。可能需要一个测试来验证，用上一个版本的 compiler 编译出来的模板代码是否可以在新版本的 runtime 中运行。以此来对用户给出一些提示和通知。

**Comment by yiminghe** [comment]
之前加过，把编译出来的代码加上编译的版本，runtime 对比下版本，不一致就提示，后来觉得麻烦，就约定 x.y.z  z 变动不需要重编译，x y 变动需要重编译，你看看怎么搞合适
