### ISSUE TITLE
支持移除命令产生的空行

### ISSUE THREAD

**Issue by luin** [xtemplate/xtemplate#62]
现在使用：
```
line 1
{{# if (bool)}}
line 2
{{/if}}
line 3
```

会生成
```
line 1

line 2

line 3
```

期望能有方法移除命令本身所在的空行，期望的结果：

```
line1
line2
line3
```

可以考虑的方法是使用类似 handlebars 的 ~ 符号：http://stackoverflow.com/questions/24317474/how-do-you-prevent-newline-added-to-handlebars-partial?stw=2 即：

```
line 1
{{~# if (bool)~}}
line 2
{{~/if~}}
line 3
```

**Comment by yiminghe** [comment]
good idea
