### ISSUE TITLE
gulp-xtemplate編譯的時候產生出不一致的pos.line

### ISSUE THREAD

**Issue by threeday0905** [xtemplate/xtemplate#64]
同樣一份模版，在gulp-xtemplate編譯的時候偶爾會產生出不同的結果如上圖：

![sample](https://cloud.githubusercontent.com/assets/3525049/7350114/032d0742-ed30-11e4-90fe-a8b58a8e96c6.png)

經排查，**可能** 是全局lastLine影響造成的，
<https://github.com/xtemplate/xtemplate/blob/master/lib/compiler.js#L117-L125>

    var lastLine = 1;
    
    function markLine(pos, source) {
      if (lastLine === pos.line) {
        return;
      }
      lastLine = pos.line;
      source.push('pos.line = ' + pos.line + ';');
    }
    
    
麻煩協助處理下。

**Comment by yiminghe** [comment]
@dead-horse review 有没问题？

**Comment by yiminghe** [comment]
fixed @4.2.4
