### ISSUE TITLE
xtemplate求支持三目运算符

### ISSUE THREAD

**Issue by myhirra** [xtemplate/xtemplate#76]

**Comment by yiminghe** [comment]
例子？ 怎么不支持了

**Comment by myhirra** [comment]
举个例子：
{{set (a = 1>2?'a':'b')}}

结果：
{ [Error: XTemplate error in file: ./x.xtpl at line 1: XTemplate error in file: ./x.xtpl syntax error at line 1:
{{set (a = 1>2?'a':'b')}}  {{a}}
--------------^
expect reduce:CLOSE, reduce:OR, reduce:AND, reduce:LOGIC_EQUALS, reduce:LOGIC_NOT_EQUALS, reduce:GE, reduce:LE, reduce:GT, reduce:LT, reduce:PLUS, reduce:MINUS, reduce:MULTIPLY, reduce:DIVIDE, reduce:MODULUS, reduce:R_PAREN, reduce:R_BRACKET, reduce:COMMA, reduce:R_BRACE] xtpl: { pos: { line: 1 }, name: './x.xtpl' } }

**Comment by yiminghe** [comment]
这不是三目么, 不如直接说 条件表达式，有时间会支持下，目前可以先用 if

欢迎 pr

**Comment by myhirra** [comment]
哈哈，失误~  已经改过来了；有时间看看

**Comment by friskfly** [comment]
提交了PR支持条件表达式  麻烦 @yiminghe @dead-horse 看看   https://github.com/xtemplate/xtemplate/pull/82

**Comment by yiminghe** [comment]
4.6.0
