### ISSUE TITLE
往block追加内容而不是重写

### ISSUE THREAD

**Issue by heeroluo** [xtemplate/xtemplate#77]
> 当编写一个 template 的时候，你可以定义 blocks，这样在子模板中可以重写掉这些 block。

请问没有一种语法或者实现方案可以往block中追加内容而不是重写呢？

**Comment by yiminghe** [comment]
https://github.com/xtemplate/xtemplate/blob/1b0321b0edcc4231b16a2d2af023df88629fcd6e/tests/browser/specs/extend.js#L64
