### ISSUE TITLE
windows loader路径解析bug

### ISSUE THREAD

**Issue by ngot** [xtemplate/xtemplate#94]
demo： https://github.com/ngot/xtpl-win-test

travis：https://travis-ci.org/ngot/xtpl-win-test/builds/210846134

appveyor： https://ci.appveyor.com/project/ngot/xtpl-win-test

linux&mac不复现，windows能够复现。

windows日志：

```
pathName: C:\projects\xtpl-win-test\view\home.xtpl
pathName: header.xtpl
```

linux日志：

```
pathName: /home/travis/build/ngot/xtpl-win-test/view/home.xtpl
pathName: /home/travis/build/ngot/xtpl-win-test/view/header.xtpl
```

**Comment by ngot** [comment]
看起来应该是这里，没有考虑Windows的兼容性 https://github.com/xtemplate/xtemplate/blob/master/src/runtime.js#L44

**Comment by friskfly** [comment]
entry 的 name 的 path 不要用 windows 的 path，path都放到loader中去处理，应该就没问题。

**Comment by ngot** [comment]
这个还是bug啊...
